version: "3.5"

services:
  db:
    container_name: postgres
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: quarkus
      POSTGRES_PASSWORD: quarkus
      POSTGRES_DB: transactions
    ports:
      - "5433:5432"
    volumes:
      - ./db-postgres/db:/var/lib/postgresql/data
      - ./db-postgres/import:/import
    networks:
      - transaction-manager

  backend:
    container_name: transaction-manager-backend
    image: quarkus/transaction-manager-jvm
    restart: unless-stopped
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://host.docker.internal:5433/transactions
      QUARKUS_DATASOURCE_USERNAME: quarkus
      QUARKUS_DATASOURCE_PASSWORD: quarkus
    ports:
      - "9092:8080"
    depends_on:
      - db
    networks:
      - transaction-manager


networks:
  transaction-manager:
    name: transaction-manager-network
    driver: bridge
