version: '3'

services:
  db:
    container_name: postgres
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: quarkus
      POSTGRES_PASSWORD: quarkus
      POSTGRES_DB: transactions
    ports:
      - "60399:5432"
    volumes:
      - ./db-postgres/db:/var/lib/postgresql/data
      - ./db-postgres/import:/import
    networks:
      - transaction-manager

  backend:
    image: quarkus/transaction-manager-jvm
    restart: unless-stopped
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/db
      QUARKUS_DATASOURCE_USERNAME: app
      QUARKUS_DATASOURCE_PASSWORD: app
    ports:
      - "9091:8080"
    depends_on:
      - db
    networks:
      - transaction-manager


networks:
  transaction-manager:
    driver: bridge
